name: Bot automation

on:
    pull_request_review:
        types:
            - submitted
            - edited

jobs:
    make-generate:
        if: github.event.sender.login == 'williamboman' && contains(github.event.review.body, '@williambotman /generate')
        runs-on: ubuntu-latest
        steps:
            - name: Clone repository
              uses: actions/checkout@v2
              with:
                  fetch-depth: 0
                  ref: ${{ github.event.pull_request.head.ref }}
                  repository: ${{ github.event.pull_request.head.repo.full_name }}
                  token: ${{ secrets.PAT }}

            - uses: rhysd/action-setup-vim@v1
              with:
                  neovim: true
                  version: v0.7.0

            - name: make generate
              run: make generate

            - uses: EndBug/add-and-commit@v9
              with:
                  author_name: William Botman
                  author_email: william+bot@redwill.se
                  message: "chore: run make generate"
                  push: true
